name: Build and test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: "1.14"
          check-latest: true

      - name: Build the project
        run: make

  unit_test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: "1.14"
          check-latest: true

      - name: Install go-junit
        run: go get -u github.com/jstemmer/go-junit-report

      - name: Run go-junit
        run: |
          go test ./... -coverprofile unit-test.out -race --tags unit |\
          go-junit-report > report.xml
      - name: Save go-unit report
        uses: actions/upload-artifact@v3
        with:
          name: report
          path: report.xml
          retention-days: 1
