name: Lint
on: push

jobs:
  golangci_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: "1.14"
          check-latest: true

      - name: Install golangci linter
        run: |
          export GOLANGCI_VERSION="1.33.0"
          curl -sLO "https://github.com/golangci/golangci-lint/releases/\
          download/v${GOLANGCI_VERSION}/golangci-lint-${GOLANGCI_VERSION}-linux-amd64.tar.gz"
          tar xfz "golangci-lint-${GOLANGCI_VERSION}-linux-amd64.tar.gz"
          mv "golangci-lint-${GOLANGCI_VERSION}-linux-amd64/golangci-lint" \
          /usr/local/bin
          rm -rf "golangci-lint-${GOLANGCI_VERSION}-linux-amd64" \
          "golangci-lint-${GOLANGCI_VERSION}-linux-amd64.tar.gz"
          unset GOLANGCI_VERSION

      - name: Install golint
        run: go get golang.org/x/lint/golint

      - name: Run golint and golangci-lint
        run: make go-lint

  yaml_lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install go
        uses: actions/setup-go@v3
        with:
          go-version: "1.14"
          check-latest: true

      - name: Install yaml_lint
        run: |
          sudo apt update
          sudo apt install -y yamllint

      - name: Run yaml_lint
        run: |
          export DEBIAN_FRONTEND="noninteractive"
          make yaml-lint
